// CODE FOR KEYPAD INPUT
// ASSUMING THE MODE FOR 8085A FOR PORTA IS I/O(MODE 0)

INPUT_KEYPAD:	   HLT

KEYPAD:	   IN 80	// TAKING INPUT FROM THE KEYPAD
	   CPI FF	// CHECKING IF ANY INPUT ENTRY
	   CZ INPUT_KEYPAD
	   CMA
	   PUSH B
	   MOV B,A
	   ANI 0F
	   CPI 04
	   JMP KEYPAD	// CALLING KEYPAD AGAIN
	   MOV A,B	// CHECKING HIGHER ORDER TERMS
	   ANI F0
	   CPI 40
	   JMP KEYPAD	// CALLING KEYPAD AGAIN
	   MOV A,B
	   POP B
	   RET
// KEYPAD MAPPING
// 00H -> KEY 0
// 03H -> KEY 4
// 30H -> KEY 12
// 33H -> KEY 16
