CODE	.EQU 0000H
UPDATE:	.ORG CODE
	LXI SP, 0FFFFH	
	PUSH PSW
	PUSH H
	; modifying the update function such that 01->x and 10->o
	LXI H,BOARD
	MOV A,M; STATUS 000000XX
	RLC
	RLC 
	INX H
	ORA M
	RLC
	RLC; STATUS 0000XXXX
	INX H
	ORA M
	RLC 
	RLC; STATUS 00XXXXXX
	INX H
	ORA M
	; GENERATED THE FIRST 8-BITS
	OUT 00H; GENERATING THE OUTPUT 
	
	INX H
	MOV A,M; STATUS 000000XX
	RLC
	RLC 
	INX H
	ORA M
	RLC
	RLC; STATUS 0000XXXX
	INX H
	ORA M
	RLC 
	RLC; STATUS 00XXXXXX
	INX H
	ORA M
	;GENERATED THE SECOND 8-BITS
	OUT 01H; GENERATING THE OUTPUT
	
	INX H	
	MOV A,M
	;GENERATED THE THIRD 8-BITS
	OUT 02H
	POP H
	POP PSW
	JMP UPDATE

BOARD:	.DB 01H,01H,01H
	.DB 01H,01H,00H
	.DB 00H,00H,01H